print("This is lab 1")
print("so it's supposed to be \"easy.\"")
print("My computer is slow so this is taking me longer that I expected, but I still like it.")
print("I\nhave\na\nlot\nof\nhomework.")
print("I like to eat vegetarian pizza\nwhich is supposed to be \"healthier.\"")
